#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ManusClaw Global Command Injector
# Makes `Manusclaw` (case-insensitive) work from ANY terminal window.
#
# Usage:
#   bash manusclaw_inject.sh          # install global command
#   bash manusclaw_inject.sh --remove # uninstall
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALL_DIR="$HOME/.local/bin"
VENV_ACTIVATE="$PWD/.venv/bin/activate"
SCRIPT_SRC="$PWD/main.py"
CMD_NAME="manusclaw"

# ── detect shell rc file ──────────────────────────────────────────────────────
detect_rc() {
  if [[ -n "${ZSH_VERSION:-}" ]] || [[ "$SHELL" == */zsh ]]; then
    echo "$HOME/.zshrc"
  elif [[ -n "${BASH_VERSION:-}" ]] || [[ "$SHELL" == */bash ]]; then
    if [[ -f "$HOME/.bashrc" ]]; then
      echo "$HOME/.bashrc"
    else
      echo "$HOME/.bash_profile"
    fi
  elif [[ -f "$HOME/.profile" ]]; then
    echo "$HOME/.profile"
  else
    echo "$HOME/.bashrc"
  fi
}

SHELL_RC="$(detect_rc)"

# ── remove ────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--remove" ]]; then
  rm -f "$INSTALL_DIR/manusclaw" \
        "$INSTALL_DIR/Manusclaw" \
        "$INSTALL_DIR/MANUSCLAW"
  # strip injected lines from rc
  if [[ -f "$SHELL_RC" ]]; then
    sed -i '/# ManusClaw global command/d' "$SHELL_RC" 2>/dev/null || \
    sed -i '' '/# ManusClaw global command/d' "$SHELL_RC"
    sed -i '/export PATH.*\.local\/bin/d' "$SHELL_RC" 2>/dev/null || \
    sed -i '' '/export PATH.*\.local\/bin/d' "$SHELL_RC"
  fi
  echo "ManusClaw global command removed."
  exit 0
fi

# ── install ───────────────────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"

# find python
PYTHON="python3"
if ! command -v python3 &>/dev/null; then
  if command -v python &>/dev/null; then PYTHON="python"; fi
fi

# find the activate script (handles venv or system pip install)
if [[ -f "$VENV_ACTIVATE" ]]; then
  ACTIVATE_LINE="source \"$VENV_ACTIVATE\""
else
  ACTIVATE_LINE="# (no venv found — using system Python)"
fi

# resolve install dir of the project
PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# write launcher
cat > "$INSTALL_DIR/$CMD_NAME" << LAUNCHER
#!/usr/bin/env bash
# ManusClaw global launcher — auto-generated by manusclaw_inject.sh
cd "$PROJ_DIR"
$ACTIVATE_LINE 2>/dev/null || true
exec $PYTHON main.py "\$@"
LAUNCHER
chmod +x "$INSTALL_DIR/$CMD_NAME"

# case-insensitive aliases
ln -sf "$INSTALL_DIR/$CMD_NAME" "$INSTALL_DIR/Manusclaw"
ln -sf "$INSTALL_DIR/$CMD_NAME" "$INSTALL_DIR/MANUSCLAW"

echo "Installed: $INSTALL_DIR/$CMD_NAME (+ Manusclaw, MANUSCLAW aliases)"

# ── ensure $INSTALL_DIR is on PATH ────────────────────────────────────────────
MARKER="# ManusClaw global command"
if ! grep -q "$MARKER" "$SHELL_RC" 2>/dev/null; then
  {
    echo ""
    echo "$MARKER"
    echo "export PATH=\"\$HOME/.local/bin:\$PATH\""
  } >> "$SHELL_RC"
  echo "Added \$HOME/.local/bin to PATH in $SHELL_RC"
fi

# ── Termux-specific ───────────────────────────────────────────────────────────
if [[ -d "/data/data/com.termux" ]]; then
  TERM_BIN="$PREFIX/bin"
  cp "$INSTALL_DIR/$CMD_NAME" "$TERM_BIN/manusclaw"
  chmod +x "$TERM_BIN/manusclaw"
  ln -sf "$TERM_BIN/manusclaw" "$TERM_BIN/Manusclaw" 2>/dev/null || true
  echo "Termux: installed to $TERM_BIN"
fi

# ── Windows / Git Bash note ───────────────────────────────────────────────────
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
  WIN_SCRIPT="$PROJ_DIR/manusclaw.bat"
  cat > "$WIN_SCRIPT" << BAT
@echo off
cd /d "$PROJ_DIR"
call .venv\\Scripts\\activate.bat 2>nul
python main.py %*
BAT
  echo ""
  echo "Windows batch script: $WIN_SCRIPT"
  echo "Add $(cygpath -w "$PROJ_DIR") to your system PATH"
  echo "Then type:  manusclaw  from any cmd or PowerShell window"
fi

# ── summary ───────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════"
echo " ManusClaw global command installed!"
echo ""
echo " Reload shell:   source $SHELL_RC"
echo " Then type:      manusclaw 'your task here'"
echo "               OR"
echo "                 Manusclaw 'your task here'"
echo "════════════════════════════════════════════════════"
